# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.copypath]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copypath"

[plugins.copyfile]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/copyfile"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-eza]
github = "z-shell/zsh-eza"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"


[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# custom
[plugins.starship]

inline = 'eval "$(starship init zsh)"'

[plugins.direnv]
inline = 'eval "$(direnv hook zsh)"'

[plugins.bindkey]
inline = 'bindkey -v'

[plugins.chpwd]
inline = 'chpwd() { ls --color=auto }'

[plugins.ocaml]
inline = '''
if (( $+command[opam])); then
  if [[ -z "$OPAM_SWITCH_PREFIX" ]]; then
    eval "$(opam env)"
  fi
fi
'''

[plugins.editor]
inline = 'export EDITOR=nvim'

[plugins.fzf]
github = "junegunn/fzf"
### devboxはsheldonより先に読み込まなきゃいけないので.zshrcに直接書く
#[plugins.devbox]
#inline = 'eval "$(devbox global shellenv)"'
